function fragilityInfo = fun0b_extractFragParam_DS2_v1(bldgID, eqLIST, LimitStateVal, figUniqueSeedForParfor)
%% For faster processing, I have now replaced fun0 by splitting it into fun0a and fun0b
% fun0a processes and saves IDA for ALL component
% fun0b extracts fragility for different threshold values and saves IDA for CTRL components
% fun0 used to process IDA for each value of the threshold and thereby repeating tons of calculations 

% figUniqueSeedForParfor is used for plotting CTRL component IDAs in different figure windows
% If executed in sequence, this problem never really arises, so a default value would suffice. 
if ~exist('figUniqueSeedForParfor', 'var')
    figUniqueSeedForParfor = 1;
end

%% sample inputs
% bldgID = '2211v03_sca2'; % bldgIDLIST{2}
% eqLIST = [6000311	6000312	6001601	6001602	6001831	6001832	6002121	6002122	6002851	6002852	6003411	6003412	6003521	6003522	6004081	6004082	6004091	6004092	6004571	6004572	6004581	6004582	6004611	6004612	6006331	6006332	6006921	6006922	6007861	6007862	6009521	6009522	6009681	6009682	6009871	6009872	6011351	6011352	6014361	6014362	6023951	6023952	6026271	6026272];
% LimitStateVal = 0.75; % for DS2, limit over chi, the ratio of max rotation to ultimate rotation capacity

% DS2 Significant Damage (Moderate Damage) % page 35 of D'ayala et al (2015)
    % the most critical column cntrols the state of the structure: the
    % limit state is attained when the rotation at one hinge of any column
    % exceeds 75% of the ultimate rotation.
%%%%%%% END OF USER INPUT

%% Calculations start
% clear; tic
baseFolder = pwd;
numEqs = size(eqLIST, 2);

%% 0. Based on building ID, read EQ-specific processed results from data file generated by fun0a (IDA, i.e., critical column damage versus Sa(Ta)
% cd H:\DamageIndex\Automated
% cd ..\..\..\DamageIndex\Automated\

[~, analysisTypeFolder, ~, ~] = returnModelFolderInfo(bldgID);
cd(analysisTypeFolder); 

for eqIndex = 1:numEqs
    eqNumber = eqLIST(eqIndex); eqFolder = sprintf('EQ_%d', eqNumber);
    cd(eqFolder);
%     eqDataFileName = sprintf('DATA_criticalColDamRat_%s_IDA_ForThisEQ.mat', strrep(num2str(round(LimitStateVal, 2), '%.2f'), '.', 'p'));
    eqDataFileName = sprintf('DATA_criticalColDamRat_IDA_ForThisEQ.mat');
    load(eqDataFileName, 'chiMax', 'saT1LIST', 'criticalColID', 'xiMax', 'criticalColID_xi');
    cd ..
%% 1. using theta_U as normalizing parameter
% 1.1 and 1.5a in fun0a_

% 1.2 (ALL) calculate ALL components for LimitStateVal
    % interpolate the obtained IDA for this TH, i.e., chiMax vs. saT1LIST at chi_DS2 = 0.75
    % A simple interpolation may not work, since IDAs are non-monotonous at times
    ix = find(chiMax  > LimitStateVal, 1);
    if isempty(ix)
        saT1_ds2_ALL(eqIndex) = saT1LIST(end);
    else
        saT1_ds2_ALL(eqIndex) = interp1([chiMax(ix-1), chiMax(ix)], ...
            [saT1LIST(ix-1), saT1LIST(ix)], LimitStateVal, 'pchip');
    end
        
% 1.3 (CTRL) for odd time history TH, store chiMax and saT1LIST, in case it is controlling
        if mod(eqIndex, 2) == 1 
            chiMax_CompOne = chiMax;
            saT1LIST_CompOne = saT1LIST;
            % chiMax_CompTwo and sasaT1LIST_CompTwo need not be assigned since 
            % chiMax and saT1LIST from current eqIndex are available in next conditional statement
        end
        
% 1.4 (CTRL) determine the controling component and plot it
        if mod(eqIndex, 2) == 0 % for every second TH, find controling component
            gmIndex = eqIndex/2;
            saT1_ds2_CompOne = saT1_ds2_ALL(eqIndex - 1);
            saT1_ds2_CompTwo = saT1_ds2_ALL(eqIndex);
            saT1_ds2_CTRL(gmIndex) = min(saT1_ds2_CompOne, saT1_ds2_CompTwo);
            
            % plot CTRL component IDA
%             figure(200 + i);
            figure(200 + figUniqueSeedForParfor);
            if saT1_ds2_CompOne < saT1_ds2_CompTwo
                plot([0, chiMax_CompOne], [0, saT1LIST_CompOne], 'b-o', 'LineWidth', 1); hold on; grid on;
            else
                plot([0, chiMax], [0, saT1LIST], 'b-o', 'LineWidth', 1); hold on; grid on;
            end
        end        
    
%% 2. using theta_Cap as normalizing parameter       
% 2.1 and 2.5a in fun0a_

% 2.2 (ALL) calculate ALL components for LimitStateVal
    % interpolate the obtained IDA for this TH, i.e., xiMax vs. saT1LIST at xi_DS2 = 0.75
    % A simple interpolation may not work, since IDAs are non-monotonous at times
    ix_xi = find(xiMax > LimitStateVal, 1);

    if isempty(ix_xi)
        saT1_ds2_ALL_xi(eqIndex) = saT1LIST(end);

    elseif ix_xi == 1
        saT1_ds2_ALL_xi(eqIndex) = saT1LIST(1);

    else
        saT1_ds2_ALL_xi(eqIndex) = interp1( ...
            [xiMax(ix_xi-1), xiMax(ix_xi)], [saT1LIST(ix_xi-1), saT1LIST(ix_xi)],  LimitStateVal, 'pchip');
    end 
    
    % ix_xi = find(xiMax  > LimitStateVal, 1);
    %     if isempty(ix_xi)
    %         saT1_ds2_ALL_xi(eqIndex) = saT1LIST(end);
    %     else
    %         saT1_ds2_ALL_xi(eqIndex) = interp1([xiMax(ix_xi-1), xiMax(ix_xi)], ...
    %                                                  [saT1LIST(ix_xi-1), saT1LIST(ix_xi)], LimitStateVal, 'pchip');
    %     end
        
% 2.3 (CTRL) for odd time history TH, store chiMax and saT1LIST, in case it is controlling
        if mod(eqIndex, 2) == 1 
            xiMax_CompOne = xiMax;
            saT1LIST_CompOne_xi = saT1LIST;
            % chiMax_CompTwo and sasaT1LIST_CompTwo need not be assigned since 
            % chiMax and saT1LIST from current eqIndex are available in next conditional statement
        end
        
% 2.4 (CTRL) determine the controling component and plot it
        if mod(eqIndex, 2) == 0 % for every second TH, find controling component
            gmIndex = eqIndex/2;
            saT1_ds2_CompOne_xi = saT1_ds2_ALL_xi(eqIndex - 1);
            saT1_ds2_CompTwo_xi = saT1_ds2_ALL_xi(eqIndex);
            saT1_ds2_CTRL_xi(gmIndex) = min(saT1_ds2_CompOne_xi, saT1_ds2_CompTwo_xi);
            
            % plot CTRL component IDA
%             figure(400 + i);
            figure(400 + figUniqueSeedForParfor);
            if saT1_ds2_CompOne_xi < saT1_ds2_CompTwo_xi
                plot([0, xiMax_CompOne], [0, saT1LIST_CompOne_xi], 'b-o', 'LineWidth', 1); hold on; grid on;
            else
                plot([0, xiMax], [0, saT1LIST], 'b-o', 'LineWidth', 1); hold on; grid on;
            end
        end
end

% 1.5b (CTRL) save CTRL component IDAs in analysis directory (chi, normalized by thetaU)        
%     figure(200 + i);
    figure(200+figUniqueSeedForParfor); 
    hx = xlabel('\chi'); hy = ylabel('Sa(Ta)');
    xlim([0 1]);
    psb_FigureFormatScript_paper; set(gca,'fontname','times');
    exportName = sprintf('criticalColDamage_chi_%s_IDA_CTRLComp', strrep(num2str(round(LimitStateVal, 2), '%.2f'), '.', 'p'));
    
    hgsave(exportName); print('-depsc', exportName); print('-dmeta', exportName);
    
        
% 1.6 Calculate statistics for ds2 for both ALL and CTRL components    
    meanLnDS2SaAllComp = exp(mean(log(saT1_ds2_ALL)));
    stDevLnDS2SaAllComp = std(log(saT1_ds2_ALL));
    minDS2LevelSaAll = min(saT1_ds2_ALL);
    maxDS2LevelSaAll = max(saT1_ds2_ALL);
    
    meanLnDS2SaCtrlComp = exp(mean(log(saT1_ds2_CTRL)));
    stDevLnDS2SaCtrlComp = std(log(saT1_ds2_CTRL));
    minDS2LevelSaCtrl = min(saT1_ds2_CTRL);
    maxDS2LevelSaCtrl = max(saT1_ds2_CTRL);
 
% 1.7 Save processed results 
%     fileName = sprintf('DATA_criticalCol_chi_%3.2f_SaAndStats.mat', chi_LimitState);
%     fileName = sprintf('DATA_criticalCol_chi_%ip%i_SaAndStats.mat', floor(LimitStateVal), int8(LimitStateVal*100));
    fileName = sprintf('DATA_criticalCol_chi_%s_SaAndStats.mat', strrep(num2str(round(LimitStateVal, 2), '%.2f'), '.', 'p'));

    save(fileName, 'saT1_ds2_ALL', 'saT1_ds2_CTRL', 'LimitStateVal', 'eqLIST', ...
        'meanLnDS2SaAllComp', 'stDevLnDS2SaAllComp', 'minDS2LevelSaAll', 'maxDS2LevelSaAll',...
        'meanLnDS2SaCtrlComp', 'stDevLnDS2SaCtrlComp', 'minDS2LevelSaCtrl', 'maxDS2LevelSaCtrl');
    fprintf('Data file saved as %s.\n', fullfile(pwd, fileName));
 
        
% 2.5b (CTRL) save CTRL component IDAs in analysis directory (xi, normalized by thetaU)        
%     figure(400 + i);
    figure(400+figUniqueSeedForParfor); 
    hx = xlabel('\xi'); hy = ylabel('Sa(Ta)');
    xlim([0 1]);
    psb_FigureFormatScript_paper; set(gca,'fontname','times');
%     exportName = sprintf('criticalColDamage_xi_%ip%i_IDA_CTRLComp', floor(LimitStateVal), int8(LimitStateVal*100));
    exportName = sprintf('criticalColDamage_xi_%s_IDA_CTRLComp', strrep(num2str(round(LimitStateVal, 2), '%.2f'), '.', 'p'));
    
    hgsave(exportName); print('-depsc', exportName); print('-dmeta', exportName);
            
% 2.6 Calculate statistics for ds2 for both ALL and CTRL components    
    meanLnDS2SaAllComp_xi = exp(mean(log(saT1_ds2_ALL_xi)));
    stDevLnDS2SaAllComp_xi = std(log(saT1_ds2_ALL_xi));
    minDS2LevelSaAll_xi = min(saT1_ds2_ALL_xi);
    maxDS2LevelSaAll_xi = max(saT1_ds2_ALL_xi);
    
    meanLnDS2SaCtrlComp_xi = exp(mean(log(saT1_ds2_CTRL_xi)));
    stDevLnDS2SaCtrlComp_xi = std(log(saT1_ds2_CTRL_xi));
    minDS2LevelSaCtrl_xi = min(saT1_ds2_CTRL_xi);
    maxDS2LevelSaCtrl_xi = max(saT1_ds2_CTRL_xi);
        
% 2.7 Save processed results 
%     fileName_xi = sprintf('DATA_criticalCol_xi_%ip%i_SaAndStats.mat', floor(LimitStateVal), int8(LimitStateVal*100));
    fileName_xi = sprintf('DATA_criticalCol_xi_%s_SaAndStats.mat', strrep(num2str(round(LimitStateVal, 2), '%.2f'), '.', 'p'));

    save(fileName_xi, 'saT1_ds2_ALL_xi', 'saT1_ds2_CTRL_xi', 'LimitStateVal', 'eqLIST', ...
        'meanLnDS2SaAllComp_xi', 'stDevLnDS2SaAllComp_xi', 'minDS2LevelSaAll_xi', 'maxDS2LevelSaAll_xi',...
        'meanLnDS2SaCtrlComp_xi', 'stDevLnDS2SaCtrlComp_xi', 'minDS2LevelSaCtrl_xi', 'maxDS2LevelSaCtrl_xi');
    fprintf('Data file saved as %s.\n', fullfile(pwd, fileName_xi));

% assign output for the function (repeated data in the .mat file as well)
    fragilityInfo.saT1_ds2_ALL = saT1_ds2_ALL;
    fragilityInfo.saT1_ds2_CTRL = saT1_ds2_CTRL;
    fragilityInfo.chi_LimitStateDS2 = LimitStateVal;
    fragilityInfo.eqLIST = eqLIST;
    
    fragilityInfo.meanLnDS2SaAllComp = meanLnDS2SaAllComp;
    fragilityInfo.stDevLnDS2SaAllComp = stDevLnDS2SaAllComp;
    fragilityInfo.minDS2LevelSaAll = minDS2LevelSaAll;
    fragilityInfo.maxDS2LevelSaAll = maxDS2LevelSaAll;
        
    fragilityInfo.meanLnDS2SaCtrlComp = meanLnDS2SaCtrlComp;
    fragilityInfo.stDevLnDS2SaCtrlComp = stDevLnDS2SaCtrlComp;
    fragilityInfo.minDS2LevelSaCtrl = minDS2LevelSaCtrl;
    fragilityInfo.maxDS2LevelSaCtrl = maxDS2LevelSaCtrl;

% xi values
    fragilityInfo.saT1_ds2_ALL_xi = saT1_ds2_ALL_xi;
    fragilityInfo.saT1_ds2_CTRL_xi = saT1_ds2_CTRL_xi;
    fragilityInfo.chi_LimitStateDS2_xi = LimitStateVal;
%     fragilityInfo.eqLIST = eqLIST;
    
    fragilityInfo.meanLnDS2SaAllComp_xi = meanLnDS2SaAllComp_xi;
    fragilityInfo.stDevLnDS2SaAllComp_xi = stDevLnDS2SaAllComp_xi;
    fragilityInfo.minDS2LevelSaAll_xi = minDS2LevelSaAll_xi;
    fragilityInfo.maxDS2LevelSaAll_xi = maxDS2LevelSaAll_xi;
        
    fragilityInfo.meanLnDS2SaCtrlComp_xi = meanLnDS2SaCtrlComp_xi;
    fragilityInfo.stDevLnDS2SaCtrlComp_xi = stDevLnDS2SaCtrlComp_xi;
    fragilityInfo.minDS2LevelSaCtrl_xi = minDS2LevelSaCtrl_xi;
    fragilityInfo.maxDS2LevelSaCtrl_xi = maxDS2LevelSaCtrl_xi;
        
    cd(baseFolder);
% close figures to avoid plotting on the same figure in case the function is repeatedly called 

close all;

% toc