function fragilityInfo = fun0b_extractFragParam_DS1_v1(bldgID, eqLIST, LimitStateVal) %, figUniqueSeedForParfor)
%% DS1 Damage Limitation (Slight Damage) Operationability % page 35 of D'ayala et al (2015)
    % the limit state is attained at the yield displacement of the
    % idealized pushober curve and we use trilinear pushover curve idealization as per 
    % ASCE 41-13 section 7.4.3.2.4 which in turn refers to FEMA 440 section 4.3

% For faster processing, I have now replaced fun0 by splitting it into fun0a and fun0b
% fun0a processes and saves IDA for ALL component
% fun0b extracts fragility for different threshold values and saves IDA for CTRL components
% fun0 used to process IDA for each value of the threshold and thereby repeating tons of calculations 

% figUniqueSeedForParfor is used for plotting CTRL component IDAs in different figure windows
% If executed in sequence, this problem never really arises, so a default value would suffice. 

% if ~exist('figUniqueSeedForParfor', 'var')
%     figUniqueSeedForParfor = 1;
% end

% clear; tic
%% sample inputs
% bldgID = '2211v03_sca2'; % bldgIDLIST{2}
% eqLIST = [6000311	6000312	6001601	6001602	6001831	6001832	6002121	6002122	6002851	6002852	6003411	6003412	6003521	6003522	6004081	6004082	6004091	6004092	6004571	6004572	6004581	6004582	6004611	6004612	6006331	6006332	6006921	6006922	6007861	6007862	6009521	6009522	6009681	6009682	6009871	6009872	6011351	6011352	6014361	6014362	6023951	6023952	6026271	6026272];
% LimitStateVal = 0.01;
% LimitStateVal = 0.01; % for DS1, limit over roof drift ratio 
%%%%%%% END OF USER INPUT

%% Calculations start
baseFolder = pwd;
numEqs = size(eqLIST, 2);

%% 0. Based on building ID, read EQ-specific processed results from data file generated by fun0a (IDA, i.e., critical column damage versus Sa(Ta)
% cd H:\DamageIndex\Automated
cd ..\..\..\DamageIndex\Automated\
[~, analysisTypeFolder, ~, ~] = returnModelFolderInfo(bldgID);
cd(analysisTypeFolder); 

for eqIndex = 1:numEqs
    eqNumber = eqLIST(eqIndex); eqFolder = sprintf('EQ_%d', eqNumber);
    cd(eqFolder);
    eqDataFileName = sprintf('DATA_roofDriftRat_IDA_ForThisEQ.mat');
    load(eqDataFileName, 'roofDriftM', 'saT1LIST');
    cd ..
% 1 (ALL) calculate ALL components for LimitStateVal
    % interpolate the obtained IDA for this TH, i.e., RDR_max vs. saT1LIST at RDR_DS1 = delta_y,eff (say, 0.9%) 
    % A simple interpolation may not work, since IDAs are non-monotonous at times
    ix = find(roofDriftM  > LimitStateVal, 1);
    if isempty(ix)
        saT1_ds1_ALL(eqIndex) = saT1LIST(end);
    elseif ix == 1 % when the limit state value is less than the first entry, interpolate between origin and first point
        saT1_ds1_ALL(eqIndex) = interp1([0, roofDriftM(ix)], ...
            [0, saT1LIST(ix)], LimitStateVal, 'pchip');
    else
        saT1_ds1_ALL(eqIndex) = interp1([roofDriftM(ix-1), roofDriftM(ix)], ...
            [saT1LIST(ix-1), saT1LIST(ix)], LimitStateVal, 'pchip');
    end
        
% 2 (CTRL) for odd time history TH, store chiMax and saT1LIST, in case it is controlling
        if mod(eqIndex, 2) == 1 
            roofDriftM_CompOne = roofDriftM;
            saT1LIST_CompOne = saT1LIST;
            % roofDriftM_CompTwo and saT1LIST_CompTwo need not be assigned since 
            % roofDriftM and saT1LIST from current eqIndex are available in next conditional statement
        end
        
% 3 (CTRL) determine the controling component and plot it
        if mod(eqIndex, 2) == 0 % for every second TH, find controling component
            gmIndex = eqIndex/2;
            saT1_ds1_CompOne = saT1_ds1_ALL(eqIndex - 1);
            saT1_ds1_CompTwo = saT1_ds1_ALL(eqIndex);
            saT1_ds1_CTRL(gmIndex) = min(saT1_ds1_CompOne, saT1_ds1_CompTwo);
            
            % plot CTRL component IDA
            figure(251); % figure(200 + figUniqueSeedForParfor);
            if saT1_ds1_CompOne < saT1_ds1_CompTwo
                plot([0, roofDriftM_CompOne], [0, saT1LIST_CompOne], 'b-o', 'LineWidth', 1); hold on; grid on;
            else
                plot([0, roofDriftM], [0, saT1LIST], 'b-o', 'LineWidth', 1); hold on; grid on;
            end
        end        
end

% 4 (CTRL) save CTRL component IDAs in analysis directory (chi, normalized by thetaU)        
    figure(251); % figure(200 + figUniqueSeedForParfor);   
    hx = xlabel('RDR_{max}'); hy = ylabel('Sa(Ta)');
%     xlim([0 1]);
    psb_FigureFormatScript_paper; set(gca,'fontname','times');
%     exportName = sprintf('roofDriftRatio_DS1_deltaY_%ip%ipc_CTRLComp', floor(LimitStateVal*100), int8(LimitStateVal*10000));
    exportName = sprintf('roofDriftRatio_DS1_deltaY_%spc_CTRLComp', strrep(num2str(round(LimitStateVal*100, 2), '%.2f'), '.', 'p'));
    hgsave(exportName); print('-depsc', exportName); print('-dmeta', exportName);
        
% 5 Calculate statistics for ds1 for both ALL and CTRL components    
    meanLnDS1SaAllComp = exp(mean(log(saT1_ds1_ALL)));
    stDevLnDS1SaAllComp = std(log(saT1_ds1_ALL));
    minDS1LevelSaAll = min(saT1_ds1_ALL);
    maxDS1LevelSaAll = max(saT1_ds1_ALL);
    
    meanLnDS1SaCtrlComp = exp(mean(log(saT1_ds1_CTRL)));
    stDevLnDS1SaCtrlComp = std(log(saT1_ds1_CTRL));
    minDS1LevelSaCtrl = min(saT1_ds1_CTRL);
    maxDS1LevelSaCtrl = max(saT1_ds1_CTRL);
 
% 1.7 Save processed results 
%     fileName = sprintf('DATA_roofDriftRat_%ip%ipc_SaAndStats.mat', floor(LimitStateVal*100), int8(LimitStateVal*10000));
    fileName = sprintf('DATA_roofDriftRat_%spc_SaAndStats.mat', strrep(num2str(round(LimitStateVal*100, 2), '%.2f'), '.', 'p'));

    save(fileName, 'saT1_ds1_ALL', 'saT1_ds1_CTRL', 'LimitStateVal', 'eqLIST', ...
        'meanLnDS1SaAllComp', 'stDevLnDS1SaAllComp', 'minDS1LevelSaAll', 'maxDS1LevelSaAll',...
        'meanLnDS1SaCtrlComp', 'stDevLnDS1SaCtrlComp', 'minDS1LevelSaCtrl', 'maxDS1LevelSaCtrl');
    fprintf('Data file saved as %s.\n', fullfile(pwd, fileName));
 

% assign output for the function (repeated data in the .mat file as well)
    fragilityInfo.saT1_ds1_ALL = saT1_ds1_ALL;
    fragilityInfo.saT1_ds1_CTRL = saT1_ds1_CTRL;
    fragilityInfo.RDR_LimitStateDS1 = LimitStateVal;
    fragilityInfo.eqLIST = eqLIST;
    
    fragilityInfo.meanLnDS1SaAllComp = meanLnDS1SaAllComp;
    fragilityInfo.stDevLnDS1SaAllComp = stDevLnDS1SaAllComp;
    fragilityInfo.minDS1LevelSaAll = minDS1LevelSaAll;
    fragilityInfo.maxDS1LevelSaAll = maxDS1LevelSaAll;
        
    fragilityInfo.meanLnDS1SaCtrlComp = meanLnDS1SaCtrlComp;
    fragilityInfo.stDevLnDS1SaCtrlComp = stDevLnDS1SaCtrlComp;
    fragilityInfo.minDS1LevelSaCtrl = minDS1LevelSaCtrl;
    fragilityInfo.maxDS1LevelSaCtrl = maxDS1LevelSaCtrl;

    cd(baseFolder);
% close figures to avoid plotting on the same figure in case the function is repeatedly called 

close all;

% toc