#----------------------------------------------------------------------------------#
# RunAllSensitivityAnalysis
#		This module runs the sensitivity anlysis that is set up in SetSensAnlysisOptions.tcl
#
# Units: 
#
# This file developed by: Curt Haselton of Stanford University
# Date: May 2004
# modified by: Prakash S Badal of IIT Bombay
# Date: 03-22-16
#
# Other files used in developing this model:
#		none
#----------------------------------------------------------------------------------#


wipe all
puts "Wiped"


# Get the fodler name so that we can come back to the folder easily later
set sensFolderName [pwd]


# Source in the sensitivity anlysis options
#source SetCollapseSensAnalysisOptionsMATLAB.tcl
#puts "SENSITIVITY Analysis options are set"

# Get data from MATLAB for this run - this opens the file that MATLAB created.
#

source psb_VarDefinitionsFromMATLAB.tcl
puts "Variable definitions retrieved from MATLAB"


# Loop and do all of the analysis
#foreach sensModel $sensModelLIST sensVariableName $sensVariableNameLIST sensVariableValue $sensVariableValueLIST  {


	# Create the file that the model will call to adjust the parameter for the sensitivity anlysis
	# 	Create the string to put into the file
		set stringForFile1	"set $sensVariableName $sensVariableValue"
		set stringForFile2	"set variableNameAlteredForSens $sensVariableName "
		set stringForFile3	"set variableValueAlteredForSens $sensVariableValue"
		puts "CHECK: Sensitivity file created to '$stringForFile1'"
		set space " "
		set commentString "# This file was created by RunCollapseSensitivityAnalysisMATLAB.tcl in the process of doing a sensitivity analysis"

		# Create the file
		set sensFile [open psb_AlterVarForColSensMATLAB(made_by_RunCollapseSensitivityAnalysisMATLAB).tcl w]
		puts $sensFile $commentString 
		puts $sensFile $space
		puts $sensFile $stringForFile1
		puts $sensFile $stringForFile2
		puts $sensFile $stringForFile3
		close $sensFile 
	
	# Now call the correct model and run the anlysis
		# Get to the right folder
		cd ..
# (11-21-15, PSB) since now sensitivity files are being saved in a folder in the prak_sensitivity folder, we need to come out of an extra folder. hence another cd .. command
		cd ..		

		set commonFolder [pwd]
#		cd $commonFolder/$sensModel


# (11-21-15, PSB) this part is for parallel computing.
# In particular, separate model folders for each EQ (generated by MATLAB) is now being referred.
		set modelFolder "model_$eqNumber"
		cd $commonFolder/$sensModel/$modelFolder

#		puts "commonFolder is $commonFolder"
#		puts "sensModel is $sensModel"
#		puts "modelFolder is $modelFolder"

		puts "Dir is [pwd]"

		# Execute the model in the folder
#		source RunColSensAnalysisMATLAB.tcl
		source psb_RunSingleColRecordSensMATLAB.tcl

		# Now go back to the sensitivity folder
		cd ..
#		cd ..
		cd $sensFolderName 

#}


# All done!!



