% 
% 
function sks_clearVarsForProcessing(saLevelsForMSAPlotLIST, maxDriftRatioForPlotLIST, saLevelsRunForCollapseAnalysis)
clear saLevelsForMSAPlotLIST maxDriftRatioForPlotLIST saLevelsRunForCollapseAnalysis