function sks_saveDATA_MSA(fileNameToSave, saLevelsForMSAPlotLIST, maxDriftRatioForPlotLIST, isCollapsedLIST, isSingularLIST, isNonConvLIST, ...
    periodUsedForScalingGroundMotions, minStoryDriftRatioForCollapseMATLAB, eqNumber, analysisType)

    save(fileNameToSave, ...
        'saLevelsForMSAPlotLIST', 'maxDriftRatioForPlotLIST', 'isCollapsedLIST', ...
        'isSingularLIST', 'isNonConvLIST', 'periodUsedForScalingGroundMotions', ...
        'minStoryDriftRatioForCollapseMATLAB', 'eqNumber', 'analysisType');
end